---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: morrigan
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland-nvidia
image-version: 42 # latest is also supported if you want new updates ASAP

stages:
    - name: nwg-dock
      from: fedora:latest
      modules:
          - type: script
            scripts:
                - installdock.sh
    - name: vial
      from: fedora:latest
      modules:
        - type: script
          scripts:
            - installvial.sh
    - name: anyrun
      from: fedora:latest
      modules:
          - type: script
            scripts:
                - installanyrun.sh

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
    - type: files
      files:
          - source: system
            destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
    - from-file: dnf.yml

    - type: default-flatpaks
      notify: true # Send notification after install/uninstall is finished (true/false)
      system:
          # If no repo information is specified, Flathub will be used by default
          install:
              - org.mozilla.firefox
              - org.gnome.Loupe
              - org.gnome.Calculator
              - org.gnome.Calendar
              - org.gnome.Contacts
              - org.gnome.clocks
          remove:
              - org.gnome.eog
      user:
          install:
              - com.discordapp.Discord
              - com.spotify.Client
              - com.bitwarden.desktop

    - type: fonts
      fonts:
          nerd-fonts:
              - FiraCode
              - Iosevka
              - JetBrainsMono

    - type: chezmoi
      repository: "https://github.com/AbooMinister25/dotfiles"
      branch: "chezmoi-config"

    - type: justfiles
      validate: false

    - type: copy
      from: nwg-dock
      src: bin/nwg-dock-hyprland
      dest: /usr/bin/
    - type: copy
      from: nwg-dock
      src: /usr/share/nwg-dock-hyprland
      dest: /usr/share/nwg-dock-hyprland
    - type: copy
      from: vial
      src: bin/Vial-v0.7.3-x86_64.AppImage
      dest: /usr/bin/
    - type: copy
      from: anyrun
      src: bin/bin/anyrun
      dest: /usr/bin
    - type: copy
      from: anyrun
      src: compiled_plugins/
      dest: /etc/anyrun/

    - type: files
      files:
        - source: system/usr
          destinations: /usr
        - source: system/etc/anyrun
          destination: /etc/anyrun/

    - type: signing # this sets up the proper policy & signing files for signed images to work fully
